# Site settings
title: "个人总结笔记"
description: "by: Yongqiang Wei"
baseurl: "" 
#change the baseurl to "" if you are using it as your user GitHub Pages
url: "https://Jueee.github.io"  


# GitHub User settings
username: Wei Yongqiang
github_username: Jueee
user_description: user_description
user_title: 每天进步一点点~~
email: hellojue@foxmail.com

# Blog Author settings
author:
  name: "Yongqiang Wei"           
  picture:        
  email: "hellojue@foxmail.com"           
  description: "努力跟上时代步伐的90后程序猿。"    
  twitter:
  facebook:
  github: "https://github.com/Jueee"         
  linkedin:
  clustrmap:      

gitpagelink:
- name: "docker 相关学习笔记"
  address: https://jueee.github.io/docker-doc/
- name: "kubernetes 相关学习笔记"
  address: https://jueee.github.io/kubernetes-doc/
- name: "设计模式相关学习笔记"
  address: https://jueee.github.io/design-patterns/
- name: "Effective Java 学习笔记"
  address: https://jueee.github.io/effective-Java/
- name: "Java 并发编程学习笔记"
  address: https://jueee.github.io/ConcurrencyWithJava/
- name: "Java 测试驱动开发学习笔记"
  address: https://jueee.github.io/JavaTestDrivenDev/
- name: "Java 8 函数式编程学习笔记"
  address: https://jueee.github.io/Java8Lambdas/

baidu_tmid: d11c8b9bc802239c2cc46ff39d3faf79
# Support for LiveRe comments system.
# You can get your uid from https://livere.com/insight/myCode (General web site)
livere_uid: MTAyMC81MDgwMC8yNzI4Mg==

highlighter: rouge
# library used for syntax highlighting
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
    
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
permalink: /:year/:month/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
      mathjax: true
      mermaid: false
      highlight: false
      numbering: false  # 文章标题前，是否有数字
      status: Completed
      layout: info
      protected: false
      commentable: true
      rss: true

exclude:
 - LICENSE.md
 - README.md
 - "*.cdf"
 - "*.nb"
 - "*.bk"
 - "*.draft.md"
